### ISSUE TITLE
[General]: Not all HuggingFace GGUF Model not available

### ISSUE THREAD

**Issue by clechristophe** [a-ghorbani/pocketpal-ai#109]
Thank you for developing this amazing application. I'd like to use several models that are available on Hugginface with a GGUF version but it seems that they are not available. Why is that ?

For example I can find some gguf models under a specific username but some are not listed.

Appreciate your response.

**Comment by a-ghorbani** [comment]
Thanks! Can you let me know which specific model you couldn’t find?

We’re looking into this. I noticed that for at least one model someone pointed out to me (Replete-LLM-V2.5-Qwen-3b-GGUF), the HF search API doesn’t include the `conversational` tag in the **search** results, even though the model has the tag (https://huggingface.co/api/models/bartowski/Replete-LLM-V2.5-Qwen-3b-GGUF).

For the reference, the app is using HF's `/api/models` endpoint for the search. Whatever results we get from this, the app should get as well. We can test it here: https://huggingface.co/spaces/enzostvs/hub-api-playground with `filter=gguf,conversational`.

<img width="1553" alt="Screenshot 2024-11-27 at 13 25 35" src="https://github.com/user-attachments/assets/6487ad8b-8c2c-45c7-97a3-05da124a3882">

**Comment by a-ghorbani** [comment]
The issues regarding models like https://huggingface.co/api/models?search=Replete-LLM-V2.5-Qwen-3b-GGUF is resolved. 

@clechristophe if you face any issues with any chat GGUF model let me know. I am going to close this issue, but feel free to reopen this if your issue still persists.
