### ISSUE TITLE
Open Sourcing project

### ISSUE THREAD

**Issue by arrrrny** [a-ghorbani/pocketpal-ai#23]
I liked your project, it is fascinating and worked pretty well on my first shot. I am impressed.

My suggestion is to open source the project and other developers can contribute and make it more useful in ways that you cant even imagine to be. I would be the first to contribute. It also gave me idea strating my own open source Flutter project like this one, if you prefer to keep closed. 

Happy coding!

**Comment by Shyamnath-Sankar** [comment]
Sure I **second** that!

**Comment by arrrrny** [comment]
@Shyamnath-Sankar I think I found it, here is a flutter package, https://github.com/davidmigloz/langchain_dart/tree/main/packages/ollama_dart

**Comment by arrrrny** [comment]
> Done!

Fantastik!

**Comment by a-ghorbani** [comment]
> > Done!
> 
> Fantastik!

Looking forward to your contributions!

**Comment by arrrrny** [comment]
I look forward to. So I assume you are using React Native? Since the code is Typescript and works well on mobile. I never used React Native, I use Flutter. This will be interesting!

**Comment by Shyamnath-Sankar** [comment]
Thanks man
