### ISSUE TITLE
[ux] Disable auto-scroll after scrolling "up" while model is generating an answer

### ISSUE THREAD

**Issue by thradya** [a-ghorbani/pocketpal-ai#39]
ChatGPT and similar apps automatically disable scrolling after scrolling upwards while the model is generating output.
Currently I can't start reading the response until it's fully generated because output is scrolling automatically. In other apps scrolling to the top stops the automatic scrolling which seems like a good solution.

**Comment by mitanshu7** [comment]
To add to this, on Android the auto scroll is quite jarring even though my phone has 120Hz refresh rate. Could the scrolling be smoothed along with the above?
