### ISSUE TITLE
 Llama 3 Models Cause App Crash on Load

### ISSUE THREAD

**Issue by yassineAbou** [a-ghorbani/pocketpal-ai#45]
When loading Llama 3 models, the app consistently crashes

**Comment by ImadSaddik** [comment]
I am also experiencing this issue. I downloaded the llama 3.2 1B model, when I click on load, the app crashes.

**Comment by thunder95** [comment]
same issue

**Comment by a-ghorbani** [comment]
@yassineAbou @ImadSaddik @thunder95, Could you please share which phone you tried?

@thunder95 also llama 3.2 from the app?

**Comment by yassineAbou** [comment]
the issue appears in all categories of Llama 3.2 . my phone  is Galaxy A15

**Comment by ImadSaddik** [comment]
I am using Vivo X50 Pro.

**Comment by a-ghorbani** [comment]
thanks guys, I’ve just released version 1.4.5 (https://github.com/a-ghorbani/pocketpal-ai/pull/72) https://play.google.com/store/apps/details?id=com.pocketpalai.
Could you please try this version and let me know if it resolves the issue?

**Comment by ImadSaddik** [comment]
Thank you @a-ghorbani, I used the `Llama 3.2 1B Instruct` model, and it seems to work with no issues.
