### ISSUE TITLE
[Bug]: App crashes when selecting Advanced settings for models.

### ISSUE THREAD

**Issue by Bestello** [a-ghorbani/pocketpal-ai#75]
The app crashes when selecting advanced options for models after the lastest update of 1.4.4

**To Reproduce**
1. Go to models
2. Click on any model
3. Click on advanced settings 
4. App crashes 

**Expected behavior**
Just crashes 

**Environment (please complete the following information):**
- Device: Nothing Phone 2
- OS: Android 14
- App Version: 1.4.4

**Comment by a-ghorbani** [comment]
Hey, thanks for reporting this! #77 will address this bug. In the meantime, you can resolve it by resetting the model list (using the `Reset Models` FAB button on the **models** page).
