### ISSUE TITLE
[Feat]: make temperature customizable

### ISSUE THREAD

**Issue by mseri** [a-ghorbani/pocketpal-ai#80]
**Description**
All models have the temperature set to 0.5, it is often convenient to play with the parameter depending on the degree of creativity needed for a task.

If I want to restructure a text or extract certain data, which is one of my common use cases, I prefer to have it less creative, while if I am brainstorming something I don’t mind letting the model wondering around the probabilities space more freely.

**Comment by a-ghorbani** [comment]
That is the default value. You can change the temperature on the model card:

![Simulator Screenshot - iPhone 15 Pro Max - 2024-11-03 at 14 14 06](https://github.com/user-attachments/assets/80800f27-9c14-4f53-a536-eea32580fe54)

If you can't change it, then it is a bug. Feel free to open a bug issue in that case.

**Comment by mseri** [comment]
Oh thanks. I had completely missed the little wedge after downloading the model! Sorry for the noise
