### ISSUE TITLE
[Bug]: Unable save changes in model template

### ISSUE THREAD

**Issue by tristan-k** [a-ghorbani/pocketpal-ai#87]
I can change the model template in the model settings but I'm unable to save my changes. There is no save option.

**Comment by sorydi3** [comment]
I could take a look on this issue. could you tell me what platform are you using?

**Comment by tristan-k** [comment]
I'm on Android 14 (OneUI 6.1) with the latest PocketPal version from the Google PlayStore. I can also do a screenrecording if this helps?

**Comment by sorydi3** [comment]
yes sure,  it would be helpful too the recording

**Comment by tristan-k** [comment]
Here is a screen recording:

https://github.com/user-attachments/assets/dbdc407d-b525-431c-9e4c-b12e00af7b21

Maybe I'm missing something but there also seems to be no UI to even save the changes.

**Comment by a-ghorbani** [comment]
@tristan-k  After you change the values, the app should save them when the `onBlur` event occurs (ie you tap somewhere outside of the text input). I am unable to reproduce this on the current version, so it might have already been resolved.

@sorydi3 Thank you for looking into this. If you are testing to see if it can be reproduced, I also suggest checking issue #83. I am unable to reproduce it there, so it might have been resolved already.

**Comment by tristan-k** [comment]
@a-ghorbani I can confirm this works indeed. I would appreciate some kind of button or hint for the user. The UI in the model settings is so crammed that its hard to hit a empty space.

**Comment by sorydi3** [comment]
> @tristan-k After you change the values, the app should save them when the `onBlur` event occurs (ie you tap somewhere outside of the text input). I am unable to reproduce this on the current version, so it might have already been resolved.
> 
> @sorydi3 Thank you for looking into this. If you are testing to see if it can be reproduced, I also suggest checking issue #83. I am unable to reproduce it there, so it might have been resolved already.

I'm unable to reproduce it either , so yeah it might be already resolved.
