### ISSUE TITLE
[Bug]: Can't load models (iOS simulator)

### ISSUE THREAD

**Issue by dalisalvador** [a-ghorbani/pocketpal-ai#94]
**Describe the bug**
Trying to run the app (fresh) on my Mac using an iPhone simulator. The app throws an error while trying to load the model:
`Error: Error: Failed to load the model`

Looks like the error is thrown on `initLlama` here: https://github.com/a-ghorbani/pocketpal-ai/blob/8244a6887111ddc17aa9922880fd4ac035b88a32/src/store/ModelStore.ts#L555

**To Reproduce**
1. Download any model
2. try to load it

**Expected behavior**
It should be able to load any model

**Screenshots **
![image](https://github.com/user-attachments/assets/8906614c-b488-4be0-b186-a5714a85c3b6)
![image](https://github.com/user-attachments/assets/bd16b5fc-a75d-467e-8b9d-fb17a00f9c33)

**Environment (please complete the following information):**
- Simulator: [iPhone 15 Pro]
- App Version: [1.5.0 (14)]

**Additional context**

**Comment by a-ghorbani** [comment]
It's a known issue in llama.cpp. It should have been resolved in the recent llama.rn. 
Removing @pocketpalai/llama.rn and trying
`yarn add llama.rn` might resolve the issue.
We need to sync llama.rn to the most recent version anyways.

**Comment by dalisalvador** [comment]
> It's a known issue in llama.cpp. It should have been resolved in the recent llama.rn. Removing @pocketpalai/llama.rn and trying `yarn add llama.rn` might resolve the issue. We need to sync llama.rn to the most recent version anyways.

1. Removed `@pocketpalai/llama.rn`
2. Replaced `@pocketpalai/llama.rn` <=> `llama.rn`

And now the app crashes (instead of throwing). There're no logs
